import { ToolExecutor, ToolDefinition, ToolResult } from '../types';

export class CalculatorTool implements ToolExecutor {
    public definition: ToolDefinition = {
        name: 'calculator',
        description: 'Evaluates mathematical arithmetic expressions (e.g. "1 / 0.01034", "1024 * 768", "15% of 850").',
        parameters: {
            type: 'object',
            properties: {
                expression: {
                    type: 'string',
                    description: 'Mathematical expression to calculate (e.g. "1/0.01034").',
                },
            },
            required: ['expression'],
        },
    };

    public async execute(args: Record<string, any>): Promise<ToolResult> {
        const start = performance.now();
        try {
            // Accept any parameter name generated by the model
            let rawExpr =
                args.expression ||
                args.num ||
                args.expr ||
                args.formula ||
                args.math ||
                args.query ||
                '';

            if (!rawExpr && Object.values(args).length > 0) {
                rawExpr = String(Object.values(args)[0]);
            }

            if (!rawExpr || typeof rawExpr !== 'string') {
                throw new Error('Valid arithmetic expression string is required.');
            }

            // Handle percentage queries (e.g. "15% of 850" -> "0.15 * 850")
            let sanitized = rawExpr
                .toLowerCase()
                .replace(/of/g, '*')
                .replace(/(\d+(\.\d+)?)%/g, '($1/100)')
                .replace(/\s+/g, '');

            // Sanitize allowed math characters
            if (!/^[0-9+\-*/().^%]+$/.test(sanitized)) {
                throw new Error(`Expression "${rawExpr}" contains unsupported characters.`);
            }

            const result = this.evaluateExpression(sanitized);

            return {
                success: true,
                data: {
                    expression: rawExpr,
                    result: parseFloat(result.toFixed(6)),
                },
                executionTimeMs: Math.round(performance.now() - start),
            };
        } catch (error) {
            return {
                success: false,
                error: error instanceof Error ? error.message : String(error),
                executionTimeMs: Math.round(performance.now() - start),
            };
        }
    }

    private evaluateExpression(expr: string): number {
        let pos = 0;

        const parseNumber = (): number => {
            let numStr = '';
            while (pos < expr.length && /[0-9.]/.test(expr[pos])) {
                numStr += expr[pos++];
            }
            return parseFloat(numStr);
        };

        const parseFactor = (): number => {
            if (expr[pos] === '(') {
                pos++;
                const val = parseExpression();
                pos++;
                return val;
            }
            if (expr[pos] === '-') {
                pos++;
                return -parseFactor();
            }
            return parseNumber();
        };

        const parseTerm = (): number => {
            let val = parseFactor();
            while (pos < expr.length && (expr[pos] === '*' || expr[pos] === '/' || expr[pos] === '^')) {
                const op = expr[pos++];
                const next = parseFactor();
                if (op === '*') val *= next;
                else if (op === '/') {
                    if (next === 0) throw new Error('Division by zero');
                    val /= next;
                } else if (op === '^') {
                    val = Math.pow(val, next);
                }
            }
            return val;
        };

        const parseExpression = (): number => {
            let val = parseTerm();
            while (pos < expr.length && (expr[pos] === '+' || expr[pos] === '-')) {
                const op = expr[pos++];
                const next = parseTerm();
                val = op === '+' ? val + next : val - next;
            }
            return val;
        };

        return parseExpression();
    }
}